name: XCS221
channels:
  - defaults
dependencies:
  - python=3.12
  - cmake=3.31.2
  - boost=1.82.0
  - notebook=7.3.2
  - tk=8.6.14
  - matplotlib=3.10.0
  - pandas=2.2.3
  - pip=25.0
  - pip:
    - osmium==4.0.2
    - cloudpickle==3.1.1
    - cycler==0.12.1
    - gymnasium==1.0.0
    - importlib-metadata==8.6.1
    - jax-jumpy==1.0.0
    - kiwisolver==1.4.8
    - numpy==2.2.2
    - packaging==24.2
    - Pillow==11.1.0
    - pygame==2.6.1
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - six==1.17.0
    - typing_extensions==4.12.2
    - zipp==3.21.0
    - keyboard==0.13.5
    - plotly==6.0.0